### ISSUE TITLE
Using the api_key parameter

### ISSUE THREAD

**Issue by vmpj** [d4be4st/swagger-ui_rails#7]
I could not find any documentation on the api_key parameter,
```
<% if defined?(api_key) %>
apiKey: '<%= api_key %>',
<% end %>
```
even though I assume it works the same as the discovery_url.

But what I really want to know is how you would suggest one gets hold of the api_key in the first place, since hard coding it would be a bad idea, and there is no input field.

Thx. 
Pieter

**Comment by d4be4st** [comment]
you can just pass your apiKey to the render function:

= render 'swagger_ui/swagger_ui', discovery_url: 'root/to/swagger_doc.json', api_key: '1231415353'

**Comment by vmpj** [comment]
OK cool. Thanks for this gem!
